import type { Metadata } from "next";
import { Geist, Geist_Mono, Quantico } from "next/font/google";
import CustomCursor from "./CustomCursor";
import "./globals.css";
import { ThemeProvider } from "./_components/ThemeProvider";
import WelcomeLoader from "./_components/WelcomeLoader";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const quantico = Quantico({
  variable: "--font-quantico",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${quantico.variable} ${geistMono.variable} ${geistSans.variable} lg:cursor-[url('/images/pointer.png')_12_12,_auto] h-full antialiased bg-black dark:bg-white`}
    >
      <body className="min-h-full flex flex-col ">
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
